[project]
name = "pybuild"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "semino", email = "semino@posteo.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pybuild = "pybuild:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
